### ISSUE TITLE
Guest Token couldn't be found after 10 retires

### ISSUE THREAD

**Issue by fishmisswater** [mahrtayyab/tweety#116]
Traceback (most recent call last):
  File "C:\python3\lib\idlelib\run.py", line 559, in runcode
    exec(code, self.locals)
  File "D:\twitter.py", line 17, in <module>
    app = Twitter("session")
  File "C:\python3\lib\site-packages\tweety\bot.py", line 34, in __init__
    self.request = self.http = Request(max_retries=10, proxy=self._proxy)
  File "C:\python3\lib\site-packages\tweety\http.py", line 21, in __init__
    self.__guest_token = self._get_guest_token(max_retries)
  File "C:\python3\lib\site-packages\tweety\http.py", line 93, in _get_guest_token
    raise GuestTokenNotFound(None, None, None, f"Guest Token couldn't be found after {max_retries} retires.")
tweety.exceptions_.GuestTokenNotFound: Guest Token couldn't be found after 10 retires.
>>> 

when code run to “app = Twitter("session")”，show this error

**Comment by mahrtayyab** [comment]
Update to latest source

**Comment by fishmisswater** [comment]
I Update to latest source everytimes run my code, I sure It's latest source

**Comment by mahrtayyab** [comment]
Uninstall and install using github source

**Comment by fishmisswater** [comment]
After I pip uninstall tweety-ns，
pip install https://github.com/mahrtayyab/tweety/archive/main.zip-- upgrade.
The problem still exists.
