### ISSUE TITLE
tweety.exceptions_.UnknownError when executing get_next_page()

### ISSUE THREAD

**Issue by mpenagar** [mahrtayyab/tweety#124]
Hi, I found a strange error while processing the results of a concrete search query (just got this error with this query, all others are working correctly).

Reproducible error code:

```
from tweety import Twitter
app = Twitter("session")
app.sign_in(<USERNAME>,<PASSWORD>)
s = app.search('euskera since:2013-10-15 until:2013-10-16 lang:eu',pages=1,wait_time=20)
print(len(s.results), s.is_next_page) # --> 20 True
more = s.get_next_page()
print(len(s.results), s.is_next_page) # --> 40 True
more = s.get_next_page()
print(len(s.results), s.is_next_page) # --> 60 True
more = s.get_next_page()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/tweety/types/search.py", line 37, in get_next_page
    response = self.client.http.perform_search(self.keyword, self.cursor, self.filter)
  File "/usr/local/lib/python3.9/site-packages/tweety/http.py", line 141, in perform_search
    response = self.__get_response__(**request_data)
  File "/usr/local/lib/python3.9/site-packages/tweety/http.py", line 73, in __get_response__
    return GenericError(
  File "/usr/local/lib/python3.9/site-packages/tweety/types/n_types.py", line 65, in __init__
    self._raise_exception()
  File "/usr/local/lib/python3.9/site-packages/tweety/types/n_types.py", line 85, in _raise_exception
    raise UnknownError(
tweety.exceptions_.UnknownError: [131] Dependency: Internal error. (131)
```

Could it be due to the fact that there are only 60 possible search results but somehow tweety thinks there should be more (`is_next_page == True`)?

**Comment by mpenagar** [comment]
Found a similar error, this time when executing the search:

```
s = app.search('euskera since:2015-05-17 until:2015-05-18 lang:eu',pages=1,wait_time=20)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/tweety/bot.py", line 178, in search
    list(search.generator())
  File "/usr/local/lib/python3.9/site-packages/tweety/types/base.py", line 46, in generator
    results = self.get_next_page()
  File "/usr/local/lib/python3.9/site-packages/tweety/types/search.py", line 37, in get_next_page
    response = self.client.http.perform_search(self.keyword, self.cursor, self.filter)
  File "/usr/local/lib/python3.9/site-packages/tweety/http.py", line 141, in perform_search
    response = self.__get_response__(**request_data)
  File "/usr/local/lib/python3.9/site-packages/tweety/http.py", line 73, in __get_response__
    return GenericError(
  File "/usr/local/lib/python3.9/site-packages/tweety/types/n_types.py", line 65, in __init__
    self._raise_exception()
  File "/usr/local/lib/python3.9/site-packages/tweety/types/n_types.py", line 85, in _raise_exception
    raise UnknownError(
tweety.exceptions_.UnknownError: [131] Dependency: Internal error. (131)
```

If I increase the search interval one day, it works:
```
s = app.search('euskera since:2015-05-18 until:2015-05-19 lang:eu',pages=1,wait_time=20)
```

**Comment by mpenagar** [comment]
Digged a little into the source code and found that the json response for the search query contains an "errors" entry, which raises the exception (`http.py` line 73):

```
>>> json['errors']
[{'message': 'Dependency: Internal error. (131)', 'locations': [{'line': 2440, 'column': 3}], 'path': ['search_by_raw_query', 'search_timeline', 'timeline', 'instructions', 0, 'entries', 6, 'content', 'itemContent', 'tweet_results', 'result', 'quoted_status_result', 'result'], 'extensions': {'name': 'DependencyError', 'source': 'Server', 'retry_after': 0, 'code': 131, 'kind': 'Operational', 'tracing': {'trace_id': '02358c96c379aded'}}, 'code': 131, 'kind': 'Operational', 'name': 'DependencyError', 'source': 'Server', 'retry_after': 0, 'tracing': {'trace_id': '02358c96c379aded'}}]
```

But the same json response contains seems to contain valid data with found tweets:

```
>>> len(json['data']['search_by_raw_query']['search_timeline']['timeline']['instructions'][0]['entries'])
19
>>> json['data']['search_by_raw_query']['search_timeline']['timeline']['instructions'][0]['entries'][0]
{'entryId': 'tweet-604652854213767168', 'sortIndex': '1724367275202445312', 'content': {'entryType': 'TimelineTimelineItem', '__typename': 'TimelineTimelineItem', 'itemContent': {'itemType': 'TimelineTweet', '__typename': 'TimelineTweet', 'tweet_results': {'result': {'__typename': 'Tweet', 'rest_id': '604652854213767168', 'core': {'user_results': {'result': {'__typename': 'User', 'id': 'VXNlcjozMjkyNDgyMjM=', 'rest_id': '329248223', 'affiliates_highlighted_label': {}, 'has_graduated_access': True, 'is_blue_verified': False, 'profile_image_shape': 'Circle', 'legacy': {'can_dm': False, 'can_media_tag': False, 'created_at': 'Mon Jul 04 19:23:51 +0000 2011', 'default_profile': False, 'default_profile_image': False, 'description': 'O pobo que canta non morre nunca.', 'entities': {'description': {'urls': []}}, 'fast_followers_count': 0, 'favourites_count': 3122, 'followers_count': 334, 'friends_count': 974, 'has_custom_timelines': False, 'is_translator': False, 'listed_count': 8, 'location': 'Deitado frente ao mar.', 'media_count': 1509, 'name': 'Ultrasensei', 'normal_followers_count': 334, 'pinned_tweet_ids_str': ['960251897859907586'], 'possibly_sensitive': False, 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/329248223/1432661343', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1490330300592930820/T0QiTCFn_normal.jpg', 'profile_interstitial_type': '', 'screen_name': 'PabloGuillan', 'statuses_count': 17953, 'translator_type': 'none', 'verified': False, 'want_retweets': False, 'withheld_in_countries': []}}}}, 'unmention_data': {}, 'edit_control': {'edit_tweet_ids': ['604652854213767168'], 'editable_until_msecs': '1432997249008', 'is_edit_eligible': True, 'edits_remaining': '5'}, 'is_translatable': False, 'views': {'state': 'Enabled'}, 'source': '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>', 'legacy': {'bookmark_count': 0, 'bookmarked': False, 'created_at': 'Sat May 30 14:17:29 +0000 2015', 'conversation_id_str': '604652854213767168', 'display_text_range': [0, 21], 'entities': {'user_mentions': [], 'urls': [], 'hashtags': [], 'symbols': []}, 'favorite_count': 0, 'favorited': False, 'full_text': 'Porofabor es euskera?', 'is_quote_status': False, 'lang': 'eu', 'quote_count': 0, 'reply_count': 0, 'retweet_count': 0, 'retweeted': False, 'user_id_str': '329248223', 'id_str': '604652854213767168'}}}, 'tweetDisplayType': 'Tweet', 'highlights': {'textHighlights': [{'startIndex': 13, 'endIndex': 20}]}}, 'feedbackInfo': {'feedbackKeys': ['1060665035']}, 'clientEventInfo': {'component': 'result', 'element': 'tweet', 'details': {'timelinesDetails': {'controllerData': 'DAACDAAFDAABDAABDAABCgABAAAAAAAAAAAAAAwAAgoAAQAAAAAAAAABCgACAjWMlsN5re0KAAVqmn01QnvxHwgABgAAAAEKAAeQkh/UbKDSbgAAAAAA'}}}}}
```

Hope this can help resolving the issue

**Comment by mahrtayyab** [comment]
Thank you so much , fix has been pushed, please update to latest source
