### ISSUE TITLE
Having some issues with certain tweets

### ISSUE THREAD

**Issue by bitog** [mahrtayyab/tweety#147]
hello,

i am using `tweet_detail` and on some tweets i am getting the following error:

```py
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    tweet_data = app.tweet_detail("https://x.com/MyroSOL/status/1747450782717243897")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/tweety/bot.py", line 576, in tweet_detail
    return Tweet(self, response, response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/tweety/types/twDataTypes.py", line 42, in new_init
    init(self, *_args, **_kwargs) # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.11/site-packages/tweety/types/twDataTypes.py", line 163, in __init__
    self._format_tweet()
  File "/lib/python3.11/site-packages/tweety/types/twDataTypes.py", line 192, in _format_tweet
    if self._tweet.get('tweet'):
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

anybody got an idea why thats happening? thanks!

**Comment by mahrtayyab** [comment]
This tweet is flagged as `NSFW` , are you logged it?

**Comment by bitog** [comment]
Yes, this is the code I used:

```py
from tweety import Twitter

app = Twitter("session")
app.connect()
print(app.user)  # My account is being shown correctly

tweet_data = app.tweet_detail("https://x.com/MyroSOL/status/1747450782717243897")
print(tweet_data.text)
```

**Comment by bitog** [comment]
Ok, I fixed it by adding a birthdate.... lol - thank you!
