### ISSUE TITLE
KeyError: 'user'

### ISSUE THREAD

**Issue by rhythm2107** [mahrtayyab/tweety#186]
```
Traceback (most recent call last):
  File "c:\Users\Rhythm\Desktop\twitter-bot\twitter_bot.py", line 3, in <module>
    app = Twitter("session")
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rhythm\AppData\Local\Programs\Python\Python312\Lib\site-packages\tweety\bot.py", line 39, in __init__
    self.session = FileSession(self, session_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rhythm\AppData\Local\Programs\Python\Python312\Lib\site-packages\tweety\session.py", line 50, in __init__
    self._load_session()
  File "C:\Users\Rhythm\AppData\Local\Programs\Python\Python312\Lib\site-packages\tweety\session.py", line 63, in _load_session
    self.user = session_data['user']
                ~~~~~~~~~~~~^^^^^^^^
KeyError: 'user'
```
Seems to not be working since a few days.

**Comment by mahrtayyab** [comment]
delete `session.tw_session` file in the folder
