### ISSUE TITLE
KeyError: 'core'

### ISSUE THREAD

**Issue by erunaheru** [mahrtayyab/tweety#19]
Getting this error sporadically. I'm not entirely sure what the impact is on the data, I have noticed some tweets missing media but I'm not sure it's related. In case it's relevant, in my actual script the "all_tweets = app.get_tweets()" is in a try block but the error is still going to the console as if it wasn't, but I'm not familiar enough with Python to know if that's normal.

```
>>> from tweety.bot import Twitter
>>> screen_name = 'SciGuySpace'
>>> app = Twitter(screen_name)
>>> all_tweets = app.get_tweets()
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tweety/types/usertweet.py", line 46, in get_next_page
    _tweets.append(Tweet(response, tweet, self.http))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tweety/types/twDataTypes.py", line 93, in __init__
    self.__formatted_tweet = self._format_tweet()
                             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tweety/types/twDataTypes.py", line 126, in _format_tweet
    quoted_tweet = self._get_quoted_tweet(is_quoted)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tweety/types/twDataTypes.py", line 215, in _get_quoted_tweet
    return Tweet(raw_response, raw_tweet, self.http)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tweety/types/twDataTypes.py", line 93, in __init__
    self.__formatted_tweet = self._format_tweet()
                             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tweety/types/twDataTypes.py", line 118, in _format_tweet
    tweet_author = self.__raw_tweet['core']
                   ~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'core'
```

**Comment by erunaheru** [comment]
I think I found it, this tweet is missing from the data: https://twitter.com/SciGuySpace/status/1650470624089784322. It appears the error occurs when a quoted tweet has been deleted.

I figured out the missing media, and as I suspected it was unrelated to this error.

**Comment by mahrtayyab** [comment]
It is fixed , do upgrade to latest version and **please** do check full documentation before upgrading

**Comment by erunaheru** [comment]
Looks good, thanks again!
