### ISSUE TITLE
create_tweet() on premium+ account limits tweet length

### ISSUE THREAD

**Issue by narodnik** [mahrtayyab/tweety#199]
```
Traceback (most recent call last):
  File "/home/xyz/src/stuff/twat/./post.py", line 35, in <module>
    message = app.create_tweet(msg, files)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xyz/.local/lib/python3.12/site-packages/tweety/utils.py", line 44, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xyz/.local/lib/python3.12/site-packages/tweety/user.py", line 581, in create_tweet
    response = self.request.create_tweet(text, files, filter_, reply_to, quote, pool, place, batch_compose)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xyz/.local/lib/python3.12/site-packages/tweety/http.py", line 406, in create_tweet
    response = self.__get_response__(**request_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xyz/.local/lib/python3.12/site-packages/tweety/http.py", line 185, in __get_response__
    return GenericError(
           ^^^^^^^^^^^^^
  File "/home/xyz/.local/lib/python3.12/site-packages/tweety/types/n_types.py", line 72, in __init__
    self._raise_exception()
  File "/home/xyz/.local/lib/python3.12/site-packages/tweety/types/n_types.py", line 92, in _raise_exception
    raise TwitterError(
tweety.exceptions.TwitterError: [186] Authorization: Tweet needs to be a bit shorter. (186)
```

I'm looking at the code in tweety, and it seems to be an error from Twitter. So maybe there's an alternative method we need to call?

How do you debug this? Are you using wireshark to examine the network traffic, or how can I examine the API?

**Comment by narodnik** [comment]
https://devcommunity.x.com/t/how-to-post-280-4000-characters-via-api-v2/191156

**Comment by narodnik** [comment]
Is this a good tool to intercept SSL traffic or do you recommend another workflow?

https://docs.mitmproxy.org/stable/overview-getting-started/

**Comment by mahrtayyab** [comment]
Yes Long tweet required to be sent to `CreateNoteTweet` , it will be added in next release

**Comment by narodnik** [comment]
BTW I notice a few differences between `builder.py` and my output above:

```
    "tweet_awards_web_tipping_enabled": false,
    "creator_subscriptions_quote_tweet_preview_enabled": false,
    "verified_phone_label_enabled": false,
```

**Comment by mahrtayyab** [comment]
https://github.com/mahrtayyab/tweety/commit/650981ce9605e6e06f2c5c1fe2db5c01a5270d2e
