### ISSUE TITLE
Get all followers for a user

### ISSUE THREAD

**Issue by narodnik** [mahrtayyab/tweety#200]
This code will only print the first page:

```python
app = Twitter("session")
app.sign_in(username, password)

user = app.get_user_info(username)
users = app.iter_user_followers(username, pages=4)

i = 0
for x in users:
    self_user, followers = x
    print(f"Page {i}")
    for follower in followers:
        print(" ", follower.username, follower.followers_count)
    print()

    if i > 5:
        break
    i += 1
```

**Comment by mahrtayyab** [comment]
Example code is working okay for me, can you please share the `username`

**Comment by narodnik** [comment]
Narodism, for me it just prints a single page then exits.

**Comment by mahrtayyab** [comment]
![image](https://github.com/user-attachments/assets/2b36f942-fd2c-4d29-aa14-e85da8b72aab)

**Comment by narodnik** [comment]
Hmm I'm not sure what's up. I tried running the script again, and now I get:
```
$ ./follow.py 
Traceback (most recent call last):
  File "/home/narodnik/src/stuff/twat/follows/./follow.py", line 10, in <module>
    app.sign_in(username, password)
  File "/home/narodnik/.local/lib/python3.12/site-packages/tweety/auth.py", line 111, in sign_in
    return self._login()
           ^^^^^^^^^^^^^
  File "/home/narodnik/.local/lib/python3.12/site-packages/tweety/auth.py", line 198, in _login
    raise DeniedLogin(response=response, message=reason)
tweety.exceptions.DeniedLogin: Suspicious login prevented. We blocked an attempt to access your account because we weren't sure it was really you.

This happens when we notice unusual login activity, like an attempt to log in too many times, or from a different location or device.

You'll need to wait before trying to log in again. Some blocks are removed automatically.

Get help with login issues.
```

**Comment by mahrtayyab** [comment]
#201
