### ISSUE TITLE
Issue when using auth_token sign in

### ISSUE THREAD

**Issue by safepre** [mahrtayyab/tweety#222]
```
from tweety import TwitterAsync
import asyncio

async def main():
    app = TwitterAsync("session")  
    await app.load_auth_token(AUTH_TOKEN)
    all_tweets = await app.get_tweets("elonmusk")
    for tweet in all_tweets:
        print(tweet)

asyncio.run(main())
```

Traceback (most recent call last):
  File "/home/boba/tweet-bot/src/tweet_async.py", line 11, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/boba/tweet-bot/src/tweet_async.py", line 6, in main
    await app.load_auth_token(AUTH_TOKEN) (I DONT WANT TO SHOW THE TOKEN BUT IM GETTING AN ERROR)
  File "/home/boba/tweet-bot/venv/lib/python3.12/site-packages/tweety/auth.py", line 128, in load_auth_token
    return await self.load_cookies(temp_cookie)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/boba/tweet-bot/venv/lib/python3.12/site-packages/tweety/auth.py", line 115, in load_cookies
    return await self.connect()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/boba/tweet-bot/venv/lib/python3.12/site-packages/tweety/auth.py", line 22, in connect
    self.user = await self.request.verify_cookies()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/boba/tweet-bot/venv/lib/python3.12/site-packages/tweety/http.py", line 325, in verify_cookies
    raise InvalidCredentials(None, None, None)
tweety.exceptions.InvalidCredentials: The Cookies are Invalid

**Comment by mahrtayyab** [comment]
https://github.com/mahrtayyab/tweety/commit/9ef0b45f89425e81e3802f44719b7b2947009d27

**Comment by safepre** [comment]
> [9ef0b45](https://github.com/mahrtayyab/tweety/commit/9ef0b45f89425e81e3802f44719b7b2947009d27)

Traceback (most recent call last):
  File "/home/boba/tweet-bot/src/tweet_async.py", line 11, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/boba/tweet-bot/src/tweet_async.py", line 6, in main
    await app.load_auth_token("56b26e4862d114d5bfdad0e6b5ecf097cab8224b")
  File "/home/boba/tweet-bot/venv/lib/python3.12/site-packages/tweety/auth.py", line 133, in load_auth_token
    return await self.load_cookies(temp_cookie)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/boba/tweet-bot/venv/lib/python3.12/site-packages/tweety/auth.py", line 115, in load_cookies
    return await self.connect()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/boba/tweet-bot/venv/lib/python3.12/site-packages/tweety/auth.py", line 22, in connect
    self.user = await self.request.verify_cookies()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/boba/tweet-bot/venv/lib/python3.12/site-packages/tweety/http.py", line 325, in verify_cookies
    raise InvalidCredentials(None, None, None)
tweety.exceptions.InvalidCredentials: The Cookies are Invalid


I still get the same error even though i already updated it

**Comment by mahrtayyab** [comment]
Please do uninstall and reinstall  `tweety-ns`

**Comment by safepre** [comment]
I did and it is not working and let me share you my session file because this is probably an interesting look
{"cookies": {"auth_token": "VALUE", "guest_id_marketing": "VALUE", "guest_id_ads": "VALUE", "personalization_id": "VALUE", "guest_id": "VALUE", "ct0": "VALUE"}, "user": null}

looks like user is still null even when i try signing in everything is being populated from the cookies object but user still remains null

**Comment by mahrtayyab** [comment]
can you please add `print(response)` on `/home/boba/tweet-bot/venv/lib/python3.12/site-packages/tweety/http.py` line 322 ,try again and share the log.

**Comment by mahrtayyab** [comment]
can you please add `traceback.print_exc()` on /home/boba/tweet-bot/venv/lib/python3.12/site-packages/tweety/http.py line 321 ,try again and share the log.

**Comment by safepre** [comment]
~/tweet-bot/src$ python tweet_async.py
NoneType: None
response line 322  {}
Traceback (most recent call last):
  File "/home/boba/tweet-bot/src/tweet_async.py", line 11, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/boba/tweet-bot/src/tweet_async.py", line 6, in main
    await app.load_auth_token(AUTH_TOKEN)
  File "/home/boba/tweet-bot/venv/lib/python3.12/site-packages/tweety/auth.py", line 133, in load_auth_token
    return await self.load_cookies(temp_cookie)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/boba/tweet-bot/venv/lib/python3.12/site-packages/tweety/auth.py", line 115, in load_cookies
    return await self.connect()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/boba/tweet-bot/venv/lib/python3.12/site-packages/tweety/auth.py", line 22, in connect
    self.user = await self.request.verify_cookies()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/boba/tweet-bot/venv/lib/python3.12/site-packages/tweety/http.py", line 326, in verify_cookies
    raise InvalidCredentials(None, None, None)
tweety.exceptions.InvalidCredentials: The Cookies are Invalid

**Comment by mahrtayyab** [comment]
run `pip install lxml`

**Comment by safepre** [comment]
Looks like I got it working, thanks!
