### ISSUE TITLE
Unable to Follow User in Version 2.0.3

### ISSUE THREAD

**Issue by Yuuzi261** [mahrtayyab/tweety#226]
## Description

When attempting to use the follow_user method in Tweety version 2.0.3, the program raises a KeyError for the headers key. This issue occurs even though the user information is successfully retrieved.

## Steps to Reproduce

1. Install Tweety version 2.0.3.

2. Use the following test script:

```py
from tweety import Twitter
import asyncio

app = Twitter('XXX')

async def main():
    await app.load_auth_token('AUTH_TOKEN')
    user = await app.get_user_info('Yuu_Zi_RoricoN')
    print(user)
    await app.follow_user(user)

asyncio.run(main())
```

3. Replace 'AUTH_TOKEN' with a valid authentication token.

4. Run the script.

## Observed Behavior

```
The script outputs the user information successfully but fails with the following traceback:

User(id=1104717123920654336, username=Yuu_Zi_RoricoN, name=ゆうじ, verified=False)
Traceback (most recent call last):
  File "D:\GitHub\Yuuzi\Tweetcord\test.py", line 12, in <module>
    asyncio.run(main())
  File "C:\Users\Yuuzi\miniconda3\envs\tweetcord\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Yuuzi\miniconda3\envs\tweetcord\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\GitHub\Yuuzi\Tweetcord\test.py", line 10, in main
    await app.follow_user(user)
  File "C:\Users\Yuuzi\miniconda3\envs\tweetcord\lib\site-packages\tweety\utils.py", line 70, in wrapper
    return await func(self, *args, **kwargs)
  File "C:\Users\Yuuzi\miniconda3\envs\tweetcord\lib\site-packages\tweety\user.py", line 886, in follow_user
    response = await self.http.follow_user(user_id)
  File "C:\Users\Yuuzi\miniconda3\envs\tweetcord\lib\site-packages\tweety\http.py", line 621, in follow_user
    request_data['headers']['content-type'] = f"application/x-www-form-urlencoded"
KeyError: 'headers'
```

## Environment

Tweety Version: 2.0.3

Python Version: 3.10.9

OS: Windows 11

**Comment by mahrtayyab** [comment]
https://github.com/mahrtayyab/tweety/commit/c1c060b1b9185ad49abf05b9a0f5eb65b42e5b05
