### ISSUE TITLE
Issues with load_cookies

### ISSUE THREAD

**Issue by rhythm2107** [mahrtayyab/tweety#228]
Been using cookie approach for a few months, was fine until Thursday.

Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\twitter-bot\twitter_bot.py", line 24, in <module>
    app.load_cookies(cookies_value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\tweety\auth.py", line 126, in load_cookies
    return self.connect()
           ~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\tweety\auth.py", line 22, in connect
    self.request.verify_cookies()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\tweety\http.py", line 226, in verify_cookies
    response = self.__get_response__(**data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\tweety\http.py", line 185, in __get_response__
    return GenericError(
        response, error_code, error_message
    )
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\tweety\types\n_types.py", line 72, in __init__
    self._raise_exception()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python313\Lib\site-packages\tweety\types\n_types.py", line 92, in _raise_exception
    raise TwitterError(
    ...<4 lines>...
    )
tweety.exceptions.TwitterError: [34] Sorry, that page does not exist

**Comment by mahrtayyab** [comment]
You are on latest version?

**Comment by rhythm2107** [comment]
That's embarrassing, was on an older version. Upgraded and works fine, cheers! Thanks for making this, great work!

**Comment by mahrtayyab** [comment]
Please do upgrade to latest version
