### ISSUE TITLE
TypeError: Union[arg, ...]: each arg must be a type. Got 1.

### ISSUE THREAD

**Issue by adihanifsdr** [mahrtayyab/tweety#25]
Hello guys, whenever i tried to test.py
```
from tweety.bot import Twitter

app = Twitter()
username = "elonmusk"

user = app.get_user_info(username)
all_tweets = app.get_tweets(username)

for tweet in all_tweets:
    print(tweet)
```

i've got this error

```
(c:\Users\myName\OneDrive\Desktop\testing\.conda) C:\Users\myName\OneDrive\Desktop\testing>python test.py             
Traceback (most recent call last):
  File "C:\Users\myName\OneDrive\Desktop\testing\test.py", line 1, in <module>
    from tweety.bot import Twitter
  File "c:\Users\myName\OneDrive\Desktop\testing\.conda\lib\site-packages\tweety\bot.py", line 4, in <module>
    from .types.n_types import Proxy
  File "c:\Users\myName\OneDrive\Desktop\testing\.conda\lib\site-packages\tweety\types\n_types.py", line 5, in <module>
    PROXY_TYPES = Union[socks.SOCKS4, socks.SOCKS5, socks.HTTP]
  File "c:\Users\myName\OneDrive\Desktop\testing\.conda\lib\typing.py", line 312, in inner
    return func(*args, **kwds)
  File "c:\Users\myName\OneDrive\Desktop\testing\.conda\lib\typing.py", line 403, in __getitem__
    return self._getitem(self, parameters)
  File "c:\Users\myName\OneDrive\Desktop\testing\.conda\lib\typing.py", line 515, in Union
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "c:\Users\myName\OneDrive\Desktop\testing\.conda\lib\typing.py", line 515, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "c:\Users\myName\OneDrive\Desktop\testing\.conda\lib\typing.py", line 176, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Union[arg, ...]: each arg must be a type. Got 1.
```

**Comment by windowsdeveloperwannabe** [comment]
Likely fixed by https://github.com/mahrtayyab/tweety/pull/23 so next release should work

**Comment by adihanifsdr** [comment]
Yes, it work when i try to manually download tweety src, and extract to my environment. Case closed.
