### ISSUE TITLE
KeyError: 'addEntries'

### ISSUE THREAD

**Issue by xin916** [mahrtayyab/tweety#36]
Please help me solve the problem of running error:
Traceback (most recent call last):
  File "D:\dyx_program\LSBN\twitter\twitter_tweety.py", line 17, in <module>
    tweets = Twitter(cookies=cookies).search('#VisitSingapore', pages = 8, wait_time=20)
  File "C:\Users\ASUS\.conda\envs\dyx_program\lib\site-packages\tweety\bot.py", line 19, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\ASUS\.conda\envs\dyx_program\lib\site-packages\tweety\bot.py", line 176, in search
    results = [i for i in search.generator()]
  File "C:\Users\ASUS\.conda\envs\dyx_program\lib\site-packages\tweety\bot.py", line 176, in <listcomp>
    results = [i for i in search.generator()]
  File "C:\Users\ASUS\.conda\envs\dyx_program\lib\site-packages\tweety\types\search.py", line 104, in generator
    this_tweets = self.get_next_page()
  File "C:\Users\ASUS\.conda\envs\dyx_program\lib\site-packages\tweety\types\search.py", line 30, in get_next_page
    thisTweets = self._parse_response(response)
  File "C:\Users\ASUS\.conda\envs\dyx_program\lib\site-packages\tweety\types\search.py", line 63, in _parse_response
    self.is_next_page = self._get_cursor(response)
  File "C:\Users\ASUS\.conda\envs\dyx_program\lib\site-packages\tweety\types\search.py", line 77, in _get_cursor
    for i in response['timeline']['instructions'][0]['addEntries']['entries']:
KeyError: 'addEntries'

**Comment by mahrtayyab** [comment]
It is fixed , do consider upgrading
