### ISSUE TITLE
Cookiejar support with new auth requirement.

### ISSUE THREAD

**Issue by amackenzie** [mahrtayyab/tweety#49]
It would be great if it supported https://docs.python.org/3/library/http.cookiejar.html inherently, so that we could easily load cookies from an exported cookies.txt or other source.

Currently, attempting to use the cookiejar gives an error:

```
cookies = MozillaCookieJar('./cookies-twitter-com.txt')
cookies.load()

app = Twitter(cookies=cookies)
```

leads to

```
Traceback (most recent call last):
  File "S:\work\twitter_follower\driver-tweety.py", line 23, in <module>
    app = Twitter(cookies=cookies)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\work\twitter_follower\__pypackages__\3.11\lib\tweety\bot.py", line 41, in __init__
    self.request = Request(max_retries=max_retires, proxy=proxy, cookies=cookies)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\work\twitter_follower\__pypackages__\3.11\lib\tweety\http.py", line 18, in __init__
    self.__session = s.Client(proxies=proxy, cookies=self._parse_cookies(cookies), timeout=60)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\work\twitter_follower\__pypackages__\3.11\lib\tweety\http.py", line 64, in _parse_cookies
    raise TypeError("cookies should be of class 'str' or 'dict' not {}".format(cookies.__class__))
TypeError: cookies should be of class 'str' or 'dict' not <class 'http.cookiejar.MozillaCookieJar'>
```

The cookiejar in this case needs to be converted manually to work, so direct support would make a lot of sense.

**Comment by mahrtayyab** [comment]
I have a better solution , full login support using username and password , will be updated tomorrow.

**Comment by bocxx** [comment]
Nice job!!

**Comment by mahrtayyab** [comment]
Added in latest release , do consider upgrading
