### ISSUE TITLE
how can i get replies?

### ISSUE THREAD

**Issue by taohuadaohongye** [mahrtayyab/tweety#50]
code:
all_tweets = app.get_tweets(username),this code can get tweets,but
all_tweets = app.get_tweets(username,replies=True) output error:
Traceback (most recent call last):
  File "D:\py\tweety-ns.py", line 11, in <module>
    all_tweets = app.get_tweets(username,replies=True)
  File "C:\Users\autumn\AppData\Roaming\Python\Python310\site-packages\tweety\bot.py", line 114, in get_tweets
    results = [i for i in userTweets.generator()]
  File "C:\Users\autumn\AppData\Roaming\Python\Python310\site-packages\tweety\bot.py", line 114, in <listcomp>
    results = [i for i in userTweets.generator()]
  File "C:\Users\autumn\AppData\Roaming\Python\Python310\site-packages\tweety\types\usertweet.py", line 80, in generator
    _, tweets = self.get_next_page()
  File "C:\Users\autumn\AppData\Roaming\Python\Python310\site-packages\tweety\types\usertweet.py", line 46, in get_next_page
    response = self.http.get_tweets(self.user_id, replies=self.get_replies, cursor=self.cursor)
  File "C:\Users\autumn\AppData\Roaming\Python\Python310\site-packages\tweety\http.py", line 117, in get_tweets
    response = self.__get_response__(**request_data)
  File "C:\Users\autumn\AppData\Roaming\Python\Python310\site-packages\tweety\http.py", line 40, in __get_response__
    return GenericError(
  File "C:\Users\autumn\AppData\Roaming\Python\Python310\site-packages\tweety\types\n_types.py", line 50, in __init__
    self._raise_exception()
  File "C:\Users\autumn\AppData\Roaming\Python\Python310\site-packages\tweety\types\n_types.py", line 60, in _raise_exception
    raise UnknownError(
tweety.exceptions_.UnknownError: [336] The following features cannot be null: responsive_web_twitter_blue_verified_badge_is_enabled

进程已结束,退出代码1
i must buy blue verified?

**Comment by mahrtayyab** [comment]
This is issue is fixed in latest update , please do consider upgrading

**Comment by fatemenajafi135** [comment]
Hi, the following piece of code doesn’t return any replies—it only returns tweets, quotes, and retweets.

```
app = TwitterAsync("session", proxy)
await app.load_cookies(COOKIE_VALUE)
tweets = await app.get_tweets(user, replies=True, pages=2)

```
Is there something I’m missing, or is this a known limitation?
Thanks! 🙏

**Comment by mahrtayyab** [comment]
![Image](https://github.com/user-attachments/assets/6ce310d8-9f49-4670-bcad-a7a4026761bd)
Yes it is supposed to be returning tweets which are sent as reply, what exactly are you looking for

**Comment by fatemenajafi135** [comment]
> ![Image](https://github.com/user-attachments/assets/6ce310d8-9f49-4670-bcad-a7a4026761bd) Yes it is supposed to be returning tweets which are sent as reply, what exactly are you looking for

But none of the returned results are replies and all of their "is_reply" fields are False.
