### ISSUE TITLE
Import Error Python 3.8.12

### ISSUE THREAD

**Issue by animemoeus** [mahrtayyab/tweety#71]
```
Python 3.8.12 (default, Jul 10 2023, 17:44:48) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tweety import Twitter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/www/python/django/animemoeus/2553f8b6399eb19f0bed3972e1bde41f_venv/lib/python3.8/site-packages/tweety/__init__.py", line 7, in <module>
    from .user import UserMethods
  File "/www/python/django/animemoeus/2553f8b6399eb19f0bed3972e1bde41f_venv/lib/python3.8/site-packages/tweety/user.py", line 8, in <module>
    class UserMethods:
  File "/www/python/django/animemoeus/2553f8b6399eb19f0bed3972e1bde41f_venv/lib/python3.8/site-packages/tweety/user.py", line 154, in UserMethods
    files: list[Union[str, UploadedMedia, tuple[str, str]]] = None,
TypeError: 'type' object is not subscriptable
>>> 
```

![image](https://github.com/mahrtayyab/tweety/assets/33395829/5a5e404f-9244-45f0-adc9-46dd0c02373e)
![image](https://github.com/mahrtayyab/tweety/assets/33395829/ab0a63d1-f865-4939-841f-38454066cc2e)

**Comment by SeptemberN** [comment]
I had this problem yesterday, and it was solved when I changed the python version to 3.10
