### ISSUE TITLE
I cannot get tweets

### ISSUE THREAD

**Issue by gridikono** [mahrtayyab/tweety#75]
I am usinig the code below to get the tweets:
from tweety import Twitter

app = Twitter("session")
app.sign_in("", "")
target_username = "elonmusk"

user = app.get_user_info(target_username)
all_tweets = app.get_tweets(user)

Error that I got is shown as below:
Traceback (most recent call last):
  File "C:\Users\Gridi\Desktop\nlp\osfa2022\Source code\ASSA.Scraper.Twitter\test.py", line 1, in <module>
    from tweety import Twitter
  File "C:\Users\Gridi\AppData\Roaming\Python\Python39\site-packages\tweety\__init__.py", line 4, in <module>
    from .bot import BotMethods
  File "C:\Users\Gridi\AppData\Roaming\Python\Python39\site-packages\tweety\bot.py", line 5, in <module>
    from .types import Proxy, UserTweets, Search, User, Tweet, Trends
  File "C:\Users\Gridi\AppData\Roaming\Python\Python39\site-packages\tweety\types\__init__.py", line 2, in <module>
    from .twDataTypes import (
  File "C:\Users\Gridi\AppData\Roaming\Python\Python39\site-packages\tweety\types\twDataTypes.py", line 10, in <module>
    from ..utils import *
  File "C:\Users\Gridi\AppData\Roaming\Python\Python39\site-packages\tweety\utils.py", line 106, in <module>
    def find_object(obj: dict, fn: Callable[[dict], bool]) -> Any | None:
TypeError: unsupported operand type(s) for |: '_SpecialForm' and 'NoneType'

What can cause it?

**Comment by mahrtayyab** [comment]
Fix : Upgrade to latest version
